config/routes.rb
Rails.application.routes.draw do
  resources :issues
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: %i[ show edit update destroy ]

  # GET /issues or /issues.json
  def index
    @issues = Issue.all
  end

  # GET /issues/1 or /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues or /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: "Issue was successfully created." }
        format.json { render :show, status: :created, location: @issue }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1 or /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: "Issue was successfully updated." }
        format.json { render :show, status: :ok, location: @issue }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1 or /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url, notice: "Issue was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def issue_params
      params.require(:issue).permit(:batch, :title, :assignee, :due_date, :weight, :confidential, :labels, :milestone, :issue_created_at, :url, :frontend, :backend, :priority, :severity, :infradev, :corrective_action, :observability, :performance, :security, :app_limits, :availability, :database, :deliverable)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_form.html.erb
<%= form_with(model: issue) do |form| %>
  <% if issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
        <% issue.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :batch %>
    <%= form.number_field :batch %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :assignee %>
    <%= form.text_field :assignee %>
  </div>

  <div class="field">
    <%= form.label :due_date %>
    <%= form.date_select :due_date %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight %>
  </div>

  <div class="field">
    <%= form.label :confidential %>
    <%= form.check_box :confidential %>
  </div>

  <div class="field">
    <%= form.label :labels %>
    <%= form.text_area :labels %>
  </div>

  <div class="field">
    <%= form.label :milestone %>
    <%= form.text_field :milestone %>
  </div>

  <div class="field">
    <%= form.label :issue_created_at %>
    <%= form.date_select :issue_created_at %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :frontend %>
    <%= form.check_box :frontend %>
  </div>

  <div class="field">
    <%= form.label :backend %>
    <%= form.check_box :backend %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>

  <div class="field">
    <%= form.label :severity %>
    <%= form.text_field :severity %>
  </div>

  <div class="field">
    <%= form.label :infradev %>
    <%= form.check_box :infradev %>
  </div>

  <div class="field">
    <%= form.label :corrective_action %>
    <%= form.check_box :corrective_action %>
  </div>

  <div class="field">
    <%= form.label :observability %>
    <%= form.check_box :observability %>
  </div>

  <div class="field">
    <%= form.label :performance %>
    <%= form.check_box :performance %>
  </div>

  <div class="field">
    <%= form.label :security %>
    <%= form.check_box :security %>
  </div>

  <div class="field">
    <%= form.label :app_limits %>
    <%= form.check_box :app_limits %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability %>
  </div>

  <div class="field">
    <%= form.label :database %>
    <%= form.check_box :database %>
  </div>

  <div class="field">
    <%= form.label :deliverable %>
    <%= form.check_box :deliverable %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/issues/edit.html.erb
<h1>Editing Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Issues</h1>

<table>
  <thead>
    <tr>
      <th>Batch</th>
      <th>Title</th>
      <th>Assignee</th>
      <th>Due date</th>
      <th>Weight</th>
      <th>Confidential</th>
      <th>Labels</th>
      <th>Milestone</th>
      <th>Issue created at</th>
      <th>Url</th>
      <th>Frontend</th>
      <th>Backend</th>
      <th>Priority</th>
      <th>Severity</th>
      <th>Infradev</th>
      <th>Corrective action</th>
      <th>Observability</th>
      <th>Performance</th>
      <th>Security</th>
      <th>App limits</th>
      <th>Availability</th>
      <th>Database</th>
      <th>Deliverable</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.batch %></td>
        <td><%= issue.title %></td>
        <td><%= issue.assignee %></td>
        <td><%= issue.due_date %></td>
        <td><%= issue.weight %></td>
        <td><%= issue.confidential %></td>
        <td><%= issue.labels %></td>
        <td><%= issue.milestone %></td>
        <td><%= issue.issue_created_at %></td>
        <td><%= issue.url %></td>
        <td><%= issue.frontend %></td>
        <td><%= issue.backend %></td>
        <td><%= issue.priority %></td>
        <td><%= issue.severity %></td>
        <td><%= issue.infradev %></td>
        <td><%= issue.corrective_action %></td>
        <td><%= issue.observability %></td>
        <td><%= issue.performance %></td>
        <td><%= issue.security %></td>
        <td><%= issue.app_limits %></td>
        <td><%= issue.availability %></td>
        <td><%= issue.database %></td>
        <td><%= issue.deliverable %></td>
        <td><%= link_to 'Show', issue %></td>
        <td><%= link_to 'Edit', edit_issue_path(issue) %></td>
        <td><%= link_to 'Destroy', issue, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New Issue</h1>

<%= render 'form', issue: @issue %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Batch:</strong>
  <%= @issue.batch %>
</p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Assignee:</strong>
  <%= @issue.assignee %>
</p>

<p>
  <strong>Due date:</strong>
  <%= @issue.due_date %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @issue.weight %>
</p>

<p>
  <strong>Confidential:</strong>
  <%= @issue.confidential %>
</p>

<p>
  <strong>Labels:</strong>
  <%= @issue.labels %>
</p>

<p>
  <strong>Milestone:</strong>
  <%= @issue.milestone %>
</p>

<p>
  <strong>Issue created at:</strong>
  <%= @issue.issue_created_at %>
</p>

<p>
  <strong>Url:</strong>
  <%= @issue.url %>
</p>

<p>
  <strong>Frontend:</strong>
  <%= @issue.frontend %>
</p>

<p>
  <strong>Backend:</strong>
  <%= @issue.backend %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @issue.priority %>
</p>

<p>
  <strong>Severity:</strong>
  <%= @issue.severity %>
</p>

<p>
  <strong>Infradev:</strong>
  <%= @issue.infradev %>
</p>

<p>
  <strong>Corrective action:</strong>
  <%= @issue.corrective_action %>
</p>

<p>
  <strong>Observability:</strong>
  <%= @issue.observability %>
</p>

<p>
  <strong>Performance:</strong>
  <%= @issue.performance %>
</p>

<p>
  <strong>Security:</strong>
  <%= @issue.security %>
</p>

<p>
  <strong>App limits:</strong>
  <%= @issue.app_limits %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @issue.availability %>
</p>

<p>
  <strong>Database:</strong>
  <%= @issue.database %>
</p>

<p>
  <strong>Deliverable:</strong>
  <%= @issue.deliverable %>
</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SourceCodeBe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>